export let Images={
    profileImage: require('../assets/images/profileIcon.png'),
    notificationImage: require('../assets/images/notificationImage.png'),
    addImage: require('../assets/images/addIcon.png'),
    searchIcon: require('../assets/images/searchIcon.png'),
    cardImage: require('../assets/images/cardImage.png'),
    shareIcon: require('../assets/images/shareIcon.png'),
    settingsIcon: require('../assets/images/settingsIcon.png'),
    calendarIcon: require('../assets/images/calendarIcon.png'),
    iconMessage: require('../assets/images/iconMessage.png'),
    arrowRight: require('../assets/images/arrowRight.png'),
    union: require('../assets/images/union.png'),
    joinMeeting: require('../assets/images/joinMeeting.png'),
    edit: require('../assets/images/edit.png'),
    addIconPurpl: require('../assets/images/addIconPurpl.png'),
    backBtn: require('../assets/images/backBtn.png'),
    arrowDown: require('../assets/images/arrow_down.png'),
    settingsIconWhite: require('../assets/images/settingsIconWhite.png'),
    colImage: require('../assets/images/colImage.png'),
    trashImage: require('../assets/images/trash.png'),
    dashboard: require('../assets/images/home.png'),
    colUsers: require('../assets/images/users.png'),
};

